name: zendesk_helper_plus
description: A Flutter plugin for the Zendesk Chat SDK v2. Provides embed chat functionality in your apps to give your mobile users access to your support team
version: 3.1.2
homepage: https://github.com/SamuelGadiel
repository: https://github.com/SamuelGadiel/zendesk_helper_plus

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.samuelgadiel.zendesk.helper.plus
        pluginClass: ZendeskHelperPlus
      ios:
        pluginClass: ZendeskHelperPlus
